/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package uk.gov.di.ipv.experian.kbv.api;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
