AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  di-ipv-cri-experian-kbv-api
  SAM Template for the experian kbv api

Globals:
  Function:
    Timeout: 60
    Runtime: java11
    MemorySize: 512
    Tracing: Active

Parameters:
  Environment:
    Description: environment name
    Default: dev
    Type: String
    AllowedValues:
      - dev
      - staging
      - integration
      - prod
    ConstraintDescription: specify dev, staging, integration or prod for environment

Mappings:
  Environments:
    dev:
      Subnets:
        - subnet-08cd07453da63f873
      SecurityGroup:
        - sg-0baf479c53ac54f59

Resources:

  ExperianKbvApi:
    Type: AWS::Serverless::Api
    Properties:
      MethodSettings:
        - LoggingLevel: INFO
          ResourcePath: '/*'
          HttpMethod: '*'
      AccessLogSetting:
        Format: '{ "requestId":"$context.requestId", "ip": "$context.identity.sourceIp", "caller":"$context.identity.caller", "user":"$context.identity.user","requestTime":"$context.requestTime", "httpMethod":"$context.httpMethod","resourcePath":"$context.resourcePath", "status":"$context.status","protocol":"$context.protocol", "responseLength":"$context.responseLength" }'
      TracingEnabled: true
      Name: !Sub "ExperianKbvApi-${Environment}"
      StageName: !Ref Environment
      OpenApiVersion: 3.0.1
      DefinitionBody:
        openapi: "3.0.1" # workaround to get `sam validate` to work
        paths: # workaround to get `sam validate` to work
          /never-created:
            options: { } # workaround to get `sam validate` to work
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: './api.yaml'
      EndpointConfiguration:
        Type: REGIONAL


  ExperianKbvQuestionRetrievalFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../lambdas/questions
      Handler: uk.gov.di.ipv.cri.experian.kbv.api.QuestionHandler::handleRequest
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: di-ipv-cri-experian-kbv-api-question
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSXrayWriteOnlyAccess
        - Statement:
            - Sid: ReadSecretsPolicy
              Effect: Allow
              Action:
                - 'secretsmanager:GetSecretValue'
              Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:/${Environment}/di-ipv-cri-experian-kbv-api/experian*'
      VpcConfig:
        SecurityGroupIds: !FindInMap [ Environments, !Ref Environment, SecurityGroup ]
        SubnetIds: !FindInMap [ Environments, !Ref Environment, Subnets ]
      Events:
        RetrieveQuestions:
          Type: Api
          Properties:
            Path: /question-request
            Method: post
            RestApiId: !Ref ExperianKbvApi

  ExperianKbvQuestionAnswerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../lambdas/answers
      Handler: uk.gov.di.ipv.cri.experian.kbv.api.QuestionAnswerHandler::handleRequest
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: di-ipv-cri-experian-kbv-api-question-answer
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSXrayWriteOnlyAccess
        - Statement:
            - Sid: ReadSecretsPolicy
              Effect: Allow
              Action:
                - 'secretsmanager:GetSecretValue'
              Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:/${Environment}/di-ipv-cri-experian-kbv-api/experian*'
      VpcConfig:
        SecurityGroupIds: !FindInMap [ Environments, !Ref Environment, SecurityGroup ]
        SubnetIds: !FindInMap [ Environments, !Ref Environment, Subnets ]
      Events:
        RetrieveQuestions:
          Type: Api
          Properties:
            Path: /question-answer
            Method: post
            RestApiId: !Ref ExperianKbvApi

  KBVFunctionsCodeSigning:
    Type: AWS::Lambda::CodeSigningConfig
    Properties:
      Description: "Code Signing for KBV API Functions"
      AllowedPublishers:
        SigningProfileVersionArns:
          - "{{resolve:ssm:/dev/credentialIssuers/cri/sam/signingProfileVersionArn}}"
      CodeSigningPolicies:
        UntrustedArtifactOnDeployment: "Enforce"

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ExperianKbvQuestionRetrievalApi:
    Description: "API Gateway endpoint URL for Prod stage for question retrieval function"
    Value: !Sub "https://${ExperianKbvApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/question-request/"
  ExperianKbvQuestionRetrievalFunction:
    Description: "Question retrieval lambda function ARN"
    Value: !GetAtt ExperianKbvQuestionRetrievalFunction.Arn
  ExperianKbvQuestionRetrievalFunctionIamRole:
    Description: "Implicit IAM Role created for question retrieval function"
    Value: !GetAtt ExperianKbvQuestionRetrievalFunction.Arn
  ExperianKbvQuestionAnswerApi:
    Description: "API Gateway endpoint URL for Prod stage for question answer function"
    Value: !Sub "https://${ExperianKbvApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/question-answer/"
  ExperianKbvQuestionAnswerFunction:
    Description: "Question answer lambda function ARN"
    Value: !GetAtt ExperianKbvQuestionAnswerFunction.Arn
  ExperianKbvQuestionAnswerFunctionIamRole:
    Description: "Implicit IAM Role created for question answer function"
    Value: !GetAtt ExperianKbvQuestionAnswerFunction.Arn
